image:
  file: .gitpod.Dockerfile

tasks:
  - command: mkdir -p /workspace/data && mongod --dbpath /workspace/data

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 3000


